source 'https://rubygems.org'

gem 'middleman', '3.4.0'
gem 'middleman-livereload', '3.4.6'
gem 'middleman-syntax', '3.0.0'
gem 'middleman-blog', '3.5.3'

# Middleman has an undeclared dependency on `tzinfo-data` for
# generating timestamps.
#
# TODO(bbannier): Remove this explicit dependency when middleman
# correctly declares its requirements.
gem 'tzinfo-data'

gem 'kramdown'

gem 'htmlentities'

gem 'therubyracer'

gem 'rake'

gem 'html-proofer'
